### ISSUE TITLE
Custom types with colon-based key-names like `cycleway:surface=*`

### ISSUE THREAD

**Issue by tordans** [hotosm/MapCampaigner#428]
I am testing with http://campaigns.hotosm.org/edit/dda67f2486ad4e0ba09fbdd458973a47

### My custom type

- Filter: `highway`
- Check: `bicycle` must be present
- Check: `cycleway:surface` must be present

### Result: Error 500

> GET http://campaigns.hotosm.org/campaign/dda67f2486ad4e0ba09fbdd458973a47/function-6 500 (INTERNAL SERVER ERROR)

### Feature request

Allow for colon-based key-names like `cycleway:surface=*`

See https://wiki.openstreetmap.org/wiki/Key:cycleway#Supplementary_details for example.

**Comment by Cybereric** [comment]
I tried to use colon-based key-names.

No 500 error for me but the created filters do not work.
In fact it worked just once!
See >>> https://campaigns.hotosm.org/campaign/3b49da3b5ba64e899215bbdb0938333d
It's the "Restore 2" filter with the key "contact: phone"

It would be great to have this opportunity because many interesting keys are of this type.

**Comment by smit1678** [comment]
This should be working now, I tested this on this campaign: https://campaigns.hotosm.org/campaign/2d9946dc09a94ee8989fb3672fec44f9. Going to close out but please reopen if this is still an issue. 

<img width="1270" alt="map campaigner - example campaign 2019-01-25 15-16-25" src="https://user-images.githubusercontent.com/796838/51754431-37919280-20b4-11e9-9fc3-026c1e743f66.png">
