### ISSUE TITLE
Split Campaign's AOI

### ISSUE THREAD

**Issue by pierrealixt** [hotosm/MapCampaigner#496]
# Problem

MapCampaigner, for the moment, can only process campaigns with a size of 320 km ².

# Solution

Split campaign AOI into sub campaigns of 200km ².
Sub campaigns will then be processed by the lambda functions: download, process, render.

**Comment by pierrealixt** [comment]
We have some constrainsts from lambda function:
- Maximum execution duration per request = 300 seconds (5 minutes)
- Ephemeral disk capacity ("/tmp" space) = 512 MB

For info, an overpass query that request buildings in New-York (320 km²) will return a response of 350Mb.

**Comment by smit1678** [comment]
To drop in some additional notes:

While there should be a limit to the size of the campaign, I do think that looking to implement some solutions that allow bigger campaigns would be useful. One use case that was flagged as something that would be helpful -- tracking editing schools across an entire country. Instead of a bunch of a smaller campaigns, one bigger campaign would be helpful to track progress across an entire country. 

So the questions might be: 
* what's the size that is too big for more sparse features (like schools)?
* what's the max size for dense features like buildings or roads? 
* can we develop a solution that factors for the potential density of the feature being tracked?
* or can we develop a solution that factors for the density of the data (i.e. smaller areas for New York versus larger areas for a more rural area)? 

cc @willemarcel

**Comment by willemarcel** [comment]
I'll do some research about the size / time consumed of requests for different data types, so we can have some information about how we can make the queries depending on the size of the AOI and of the type of the data we are querying. 

For example, by the NY stats mentioned by @pierrealixt, 1km² has 1.09 MB. We could do it for some other areas, for example Nairobi, and calculate the amount of time that overpass takes to return the data and check what is the limit for each type of query (buildings, roads, pois, something more?).

**Comment by willemarcel** [comment]
First analysis querying buildings in Sao Paulo (official data was imported into OSM) and in Dar es Salaam. The density of buildings in Dar es Salaam is 2x larger. Sao Paulo buildings are approximately 3 ttimes more dense than New York.

The good news are that the overpass server never failed to return a query result. The larger query I have done took 11 minutes and returned 378.8 MB.

@pierrealixt Can the time limit of 300 seconds be increased? Does [that param](https://github.com/hotosm/MapCampaigner/blob/develop/.travis/deploy_lambda_functions.py#L166) work? Is the data compressed to a zip file in the `/tmp` 512 MB partition?

The query results for buildings are below. I'll do some research for `highway=*` tagged features tomorrow.

- Dar es Salaam

  - (-6.7979427023539785,39.23076152801514,-6.793127337028579,39.23642635345459)
  Sq. Kilometers: 0.34
  3.0 MB - 12640 nodes - 2134 ways
  
  - (-6.798347531754215,39.230525493621826,-6.793063415925636,39.24136161804199)
  Sq. Kilometers: 0.7
  6.5 MB - 27645 nodes - 4510 ways
  
  - (-6.7978787818911925,39.23007488250732,-6.790378721931974,39.24337863922119)
  Sq. Kilometers 1.23
  10.8MB - 45902 nodes - 7441 ways
  
  - (-6.8038872682258305,39.22737121582031,-6.789057676531279,39.24715518951416)
  time: 27.879331 seconds
  3.61 sq. km
  31.4 MB - 132870 nodes - 22118 ways
  
  - (-6.808830363742088,39.22715663909912,-6.788461074193963,39.248828887939446)
  time: 32.412282 seconds
  5.43 sq. km
  46.5 MB - 196381 nodes - 32852 ways
  
  - (-6.816244911533783,39.22101974487305,-6.78641557485229,39.25243377685546)
  time: 02:37.104594
  11.53 sq. km
  88.1 MB - 371399 nodes - 61444 ways
  
  - (-6.818886849131594,39.21913146972656,-6.783347309546315,39.253034591674805)
  time: 03:32.437550
  14.83 sq. km
  107.7 MB - 453062 nodes - 74464 ways
  
  - (-6.822040110420903,39.21887397766113,-6.781898399690813,39.25612449645996)
  time: 04:02.874876
  18.4 sq. km
  131.2 MB - 553416 nodes - 90467 ways


- Sao Paulo

  - (-23.57956358280368,-46.68571472167969,-23.5279496678469,-46.633872985839844)
  time: 03:38.502688
  30.4 sq. km
  117.4 MB - 510004 nodes - 63971 ways

  - (-23.599857401784767,-46.698074340820305,-23.517404089550542,-46.57997131347656)
  time 11:11.510881
  110.62 sq. km
  378.8 MB - 1618174 nodes - 233506 ways

**Comment by smit1678** [comment]
thanks for this analysis @willemarcel. After your roads analysis, what do you think is the right direction? Split the AOI based on a size that will work well? Should we still keep an upper size limit? Places like Jakarta are like at least 700 sqkm.

**Comment by willemarcel** [comment]
@smit1678 I saw in the [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) that the `/tmp` dir is limited in 512 MB and the maximum timeout setting is 15 minutes. So, yes, we'll need to set an area limit.

I'll finish the roads query analysis and then verify how we can aggregate the result of multiple lambda functions.

**Comment by willemarcel** [comment]
About the POI queries, as the distribution of POI's doesn't follow a pattern and can be very different depending of the place and of the POI type, I suggest we add a try back splitting the area if the query failed.

Some results from the `highway=*` (ways only) query analysis below. I tried to query all the Tanzania roads and it failed due to the amount of RAM needed by the operation on the server. I think we can limit the roads queries to 2500 sq.km, what in the case of Tokyo, would return 350 MB of data.

- Berlin

  - (51.97134580885172,12.65625,52.74294319885714,14.183349609375)
  Time 28.48 seconds
  120.54 sq. km
  42.1 MB - 140920 nodes - 47662 ways

  - (52.338695481504814,13.27423095703125,52.618891536583035,13.646392822265625)
  Time 53.40 seconds
  787.03 sq. km
  128 MB - 456976 nodes - 137527 ways

- Sao Paulo

  - (-23.65836152272883,-46.80313110351562,-23.439309076076434,-46.395263671875)
  Time 01:35
  1015 sq. km
  117.3 MB - 464104 nodes - 97264 ways

- Tokyo

  - (35.64055713458091,139.37530517578122,36.12567399853604,139.90264892578125)
  Time 02:08
  2568 sq. km
  361 MB - 1405064 nodes - 394316 ways

**Comment by willemarcel** [comment]
Me and @smit1678 discussed about it last week and we decided that we will not split the AOI's anymore, but operate in the lambda functions disk size limit of 512 MB: https://github.com/hotosm/MapCampaigner/issues/687
