### ISSUE TITLE
Calculate Areas Covered

### ISSUE THREAD

**Issue by pierrealixt** [hotosm/MapCampaigner#573]
# Problem

Areas Covered calculation doesnt work anymore.

# Solution

Implement again.

**Comment by pierrealixt** [comment]
@smit1678 Some questions to be sure we're on the same track:
An area is said to be covered when all the features in this area are 100% completed?
A campaign AOI is composed of two areas. One of them is 100% completed so the percentage of areas covered would be 50%?

Thanks

**Comment by smit1678** [comment]
@pierrealixt Originally it was based on the team/area tracking. Instead of the metric being focused on "areas completed" it as more about the percentage of areas that were covered/visited by field teams. For example, with campaigns that have the AOI split into multiple sections, the areas covered would correspond to the Status of each area -- incomplete or complete. In this example, https://campaigns.hotosm.org/campaign/b2ac7f8f58954091a606fc6a4e990b06, there are four areas with teams assigned. If one team is completed with their area, the project manager would then mark the area complete and then the campaign page would show 25% complete. 

<img width="1187" alt="map campaigner 2018-11-12 04-42-49" src="https://user-images.githubusercontent.com/796838/48348196-366ccf80-e646-11e8-97c2-ac99dff2c103.png">
