### ISSUE TITLE
Features captured outside of AOI

### ISSUE THREAD

**Issue by smit1678** [hotosm/MapCampaigner#596]
Map shows features that are outside of the AOI. Seen on this example: https://campaigns.hotosm.org/campaign/dd7b3627dc6942dc9798ea094f8c680b. 

Additionally, it looks like this is just for the `Buildings` layer and not for the `Water Points` layer. 

<img width="1361" alt="map campaigner - open cities monrovia - clara town 2018-11-08 11-40-40" src="https://user-images.githubusercontent.com/796838/48196807-864c4d80-e34b-11e8-9d1c-d811d45c6308.png">

**Comment by pierrealixt** [comment]
It seems the issue is due to simplify polygons where there is more than one area in the geojson.
https://github.com/hotosm/MapCampaigner/blob/develop/lambda_functions/download/overpass_data/campaign.py#L64

Here's the implified polygon overpass query that returns too much:
```
[out:xml];(way["building"](poly:"6.32605603887035 -10.798687487914801 6.330074039250473 -10.799484490372443 6.328869823110915 -10.793670838079265 6.326176721297491 -10.794370960931362 6.32490202785451 -10.797173714906723 6.32605603887035 -10.798687487914801");node["building"](poly:"6.32605603887035 -10.798687487914801 6.330074039250473 -10.799484490372443 6.328869823110915 -10.793670838079265 6.326176721297491 -10.794370960931362 6.32490202785451 -10.797173714906723 6.32605603887035 -10.798687487914801"););(._;>;);out meta;
```

And here the non-simplified polygon overpass query that returns less. 
```
[out:xml];(way["building"](poly:"6.32605603887035 -10.798687487914801 6.326219237344776 -10.798738728441336 6.326354284963692 -10.798894838146486 6.326428316646669 -10.798953026655386 6.326499218922724 -10.79903356262496 6.326530657798208 -10.799058063987482 6.326623897172828 -10.799016387794277 6.32680363562726 -10.798936048147565 6.326983431053781 -10.798855682979035 6.327127969857671 -10.798789219808556 6.328141016939881 -10.798291880698212 6.3286954717131785 -10.799683497100139 6.32883477134873 -10.799980754050639 6.3291469503261855 -10.799855742424725 6.329475441150602 -10.799724198627414 6.329725808256619 -10.799623939313168 6.329923511457468 -10.799544769172655 6.330074039250473 -10.799484490372443 6.329969193254512 -10.79922190767912 6.3298823905844515 -10.799034598570353 6.3297815620873825 -10.798786257983132 6.329650453103299 -10.798472767110306 6.3295536786341104 -10.798228508405996 6.329450836980952 -10.797974062703577 6.329331553471306 -10.797734815281123 6.329258962525996 -10.797589219708977 6.32913579106762 -10.797330626056812 6.329056599926028 -10.797163142389826 6.3288771452645145 -10.796783608954527 6.328970659128475 -10.796271025650269 6.329080374129091 -10.79571444141225 6.329141677706024 -10.79538936206923 6.3291818903907755 -10.795176122547309 6.32920747580737 -10.794834715118183 6.329111176588555 -10.794452233053029 6.329043222933639 -10.794106436800657 6.328954678907328 -10.79383374781822 6.328869823110915 -10.793670838079265 6.328727502701606 -10.793658150763983 6.328409945090514 -10.79374242837593 6.328006866913895 -10.793854870114313 6.3278572644768225 -10.793889321100885 6.327412816455547 -10.793991670175712 6.3270673232717085 -10.793837399775827 6.326884405252435 -10.793802212826785 6.326636568401639 -10.793720049798788 6.326534579006264 -10.793807104321283 6.32642509989724 -10.794005895350697 6.326327871887856 -10.794182440951174 6.326176721297491 -10.794370960931362 6.326115027673861 -10.794567920306706 6.325973100276733 -10.794805566526446 6.325865463749648 -10.794985795262715 6.325720005303081 -10.795251411777022 6.325673376294077 -10.79533655928889 6.325616565871938 -10.795440298655032 6.3255543669797705 -10.795553877768246 6.325483101535352 -10.795718120074943 6.325408832146295 -10.79588928520814 6.32535017852597 -10.796024461307486 6.3253042547809954 -10.796130299503686 6.325273834758481 -10.796226195446698 6.32519733974093 -10.796467337879587 6.325078082930274 -10.796840961401163 6.32490202785451 -10.797173714906723 6.325014694354124 -10.797527792952003 6.325184797540248 -10.797739780706502 6.325333215743781 -10.797900368482848 6.325711133079187 -10.798088055269426 6.325924952112553 -10.798459664181609 6.32605603887035 -10.798687487914801");node["building"](poly:"6.32605603887035 -10.798687487914801 6.326219237344776 -10.798738728441336 6.326354284963692 -10.798894838146486 6.326428316646669 -10.798953026655386 6.326499218922724 -10.79903356262496 6.326530657798208 -10.799058063987482 6.326623897172828 -10.799016387794277 6.32680363562726 -10.798936048147565 6.326983431053781 -10.798855682979035 6.327127969857671 -10.798789219808556 6.328141016939881 -10.798291880698212 6.3286954717131785 -10.799683497100139 6.32883477134873 -10.799980754050639 6.3291469503261855 -10.799855742424725 6.329475441150602 -10.799724198627414 6.329725808256619 -10.799623939313168 6.329923511457468 -10.799544769172655 6.330074039250473 -10.799484490372443 6.329969193254512 -10.79922190767912 6.3298823905844515 -10.799034598570353 6.3297815620873825 -10.798786257983132 6.329650453103299 -10.798472767110306 6.3295536786341104 -10.798228508405996 6.329450836980952 -10.797974062703577 6.329331553471306 -10.797734815281123 6.329258962525996 -10.797589219708977 6.32913579106762 -10.797330626056812 6.329056599926028 -10.797163142389826 6.3288771452645145 -10.796783608954527 6.328970659128475 -10.796271025650269 6.329080374129091 -10.79571444141225 6.329141677706024 -10.79538936206923 6.3291818903907755 -10.795176122547309 6.32920747580737 -10.794834715118183 6.329111176588555 -10.794452233053029 6.329043222933639 -10.794106436800657 6.328954678907328 -10.79383374781822 6.328869823110915 -10.793670838079265 6.328727502701606 -10.793658150763983 6.328409945090514 -10.79374242837593 6.328006866913895 -10.793854870114313 6.3278572644768225 -10.793889321100885 6.327412816455547 -10.793991670175712 6.3270673232717085 -10.793837399775827 6.326884405252435 -10.793802212826785 6.326636568401639 -10.793720049798788 6.326534579006264 -10.793807104321283 6.32642509989724 -10.794005895350697 6.326327871887856 -10.794182440951174 6.326176721297491 -10.794370960931362 6.326115027673861 -10.794567920306706 6.325973100276733 -10.794805566526446 6.325865463749648 -10.794985795262715 6.325720005303081 -10.795251411777022 6.325673376294077 -10.79533655928889 6.325616565871938 -10.795440298655032 6.3255543669797705 -10.795553877768246 6.325483101535352 -10.795718120074943 6.325408832146295 -10.79588928520814 6.32535017852597 -10.796024461307486 6.3253042547809954 -10.796130299503686 6.325273834758481 -10.796226195446698 6.32519733974093 -10.796467337879587 6.325078082930274 -10.796840961401163 6.32490202785451 -10.797173714906723 6.325014694354124 -10.797527792952003 6.325184797540248 -10.797739780706502 6.325333215743781 -10.797900368482848 6.325711133079187 -10.798088055269426 6.325924952112553 -10.798459664181609 6.32605603887035 -10.798687487914801"););(._;>;);out meta;
```

However this request still fetches features out of AOI...
![capture d ecran 2018-11-15 a 07 15 22](https://user-images.githubusercontent.com/35932320/48531777-50a4e880-e8a6-11e8-8e28-57daa9892f15.png)

**Comment by timlinux** [comment]
Ok So I had a look over this with @pierrealixt

We have the current workflow where the AOI polygons are first simplified before sending them to overpass and then the result overfits the number of buildings retrieved relative to the original polygon. In order to fix this we will need to filter (via an intersection geometry operation) the results returned from overpass. This is a little complex since we do not want to deploy OGR in amazaon lambda functions so we need to find a 'pure' shapely way to get the data fitted to the non-simplified poygons.  With this example:

https://gist.github.com/robintw/9366322

It look slike we can convert the .OSM data to a shapefile for use in shapely. Then we would need to figure out how to turn it back from shp to .osm for the lambda function to return at the end of the process.

Perhaps another way would be to use the intersection operation to identify all the features NOT contained in the AOI, get their node/way ids and then remove them from the .osm file by direct .xml file manipulation.

**Comment by willemarcel** [comment]
Hi @timlinux ,
Your code goes in a good way, but I think it's not worth to convert it to shapefile and write the file to the system. With Shapely, you can just do the geospatial analysis

```
building = Polygon(coords)
building.intersects(campaing_area)
```

That way you can just iterate over the xml elements and filter it. To write it back to a `.osm` file, I think the better option is to start a new ET.Element and add the filtered children and write it. Maybe it can help: https://stackoverflow.com/questions/3605680/creating-a-simple-xml-file-using-python#3605831

Let me know if you need help, @pierrealixt

**Comment by timlinux** [comment]
Hi @willemarcel 

Thanks - yes that is the approach that @pierrealixt has been taking (constructing polygons in-memory and then doing a containment check).

For your second suggestion, I think we will compile a list of nodes / ways to drop in a first parse and then rebuild the .osm file in a second pass.

Regards

Tim

**Comment by timlinux** [comment]
In addition @pierrealixt will need to check that for campaings that currently have no problem, they continue to work as before.

Time estimate:  8 hours

**Comment by pierrealixt** [comment]
I worked on this issue today and the results are not what I expected.
Here's what the program does:
- parse the OSM file
- create polygons based on `node` and `way` tags
- check if those polygons are within the campaign polygon. I've tried the following Shapely methods: `within`, `contains`, `intersects` and I got the same result.
- rewrite an OSM file without the outside polygons

The script found 77 polygons outside the campaign polygon. 

Here's the result: 
<img width="796" alt="screen shot 2019-01-08 at 14 24 45" src="https://user-images.githubusercontent.com/35932320/50840886-2b939a00-136c-11e9-8145-e8734f97d7cb.png">
Some polygons that were outside did get removed. Not all of them though. 
Some polygons that were inside did get removed.

Here's the map before running the script:
<img width="741" alt="screen shot 2019-01-08 at 17 43 47" src="https://user-images.githubusercontent.com/35932320/50841268-fe93b700-136c-11e9-9d46-eb590fc495c1.png">

Has someone an idea?

**Comment by pierrealixt** [comment]
It works!
<img width="748" alt="screen shot 2019-01-09 at 08 03 35" src="https://user-images.githubusercontent.com/35932320/50879954-700f4c00-13e5-11e9-855e-7acf0762116b.png">


I think the error comes from [this method].(https://github.com/hotosm/MapCampaigner/blob/c433dd2c35289d22278fb288057791cbe94c6a47/lambda_functions/download/overpass_data/campaign.py#L67)
Somehow the joined_polygons that is returned isn't correct. 
So I decided to check if a polygon (a building) is inside one of the polygon (area) of the campaign.

We're using the same method to create the overpass query so that's why we have this problem in the first place.

**Comment by pierrealixt** [comment]
For my test, I used an OSM file from last December.
I computed the campaign in my local environment so it fetched fresh data from overpass and I got a weird result: half of the features in the campaign's areas are gone. 
<img width="702" alt="screen shot 2019-01-09 at 09 55 58" src="https://user-images.githubusercontent.com/35932320/50885148-90df9d80-13f5-11e9-952a-5be641431c22.png">

First I thought that my script removed too many features but then I computed the campaign in production (campaign is inactive since December 19) and I got the same result:
(the production doesn't remove features outside aoi)

<img width="605" alt="screen shot 2019-01-09 at 10 02 05" src="https://user-images.githubusercontent.com/35932320/50885170-a785f480-13f5-11e9-95cd-526f2e86eb5c.png">

https://campaigns.hotosm.org/campaign/dd7b3627dc6942dc9798ea094f8c680b

@smit1678 any idea?

**Comment by smit1678** [comment]
> The coordinates are empty!

@pierrealixt Is this an issue with the data or an issue with how we're generating the geojson? 

So here's an odd thing with the data: 

Some of the buildings in the area that is missing have `Source` tags on the nodes. Example: [way](https://www.openstreetmap.org/way/625598948#map=19/6.32712/-10.79614), and [node](https://www.openstreetmap.org/node/5906720598)

But in the areas that are working, the individual nodes of the buildings do not have attribute tags on the nodes: [way](https://www.openstreetmap.org/way/625654421), [node](https://www.openstreetmap.org/node/5907159447)

**Comment by pierrealixt** [comment]
you're right @smit1678 !
I'm working on a patch.
