### ISSUE TITLE
generate gpx of AOI

### ISSUE THREAD

**Issue by russbiggs** [hotosm/MapCampaigner#724]
generate gpx of AOI for loading into iD Editor

**Comment by russbiggs** [comment]
Since this functionality is only to help with linking to iDeditor we can probably offload this work to the client via a library like this:
https://github.com/tyrasd/togpx

**Comment by JorgeMartinezG** [comment]
@russbiggs I think it would be better to make flask generate the gpx instead of the javscript client. The reason is that Id editor accepts an url to the gpx:

https://github.com/openstreetmap/iD/blob/master/API.md

So, the goal would be to create an endpoint within flask to return the gpx (xml format). Tasking manager has an API endpoint to generate the gpx from database. For MC it would be to use the campaign geojson from s3.

https://github.com/hotosm/tasking-manager/blob/develop/server/services/mapping_service.py#L194

**Comment by russbiggs** [comment]
@JorgeMartinezG you're right i thought it was encoded in the URL.  I'll move this back to backend list
